name: Clojure Test CI

on:
  push:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run Cloverage
      run: lein cloverage --no-html --codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./target/coverage/
        files: ./codecov.json
        verbose: true
